package us.dit.ass.primeraconsultaneurologica;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class DN4 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DN4_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "DN4_ID_SEQ", name = "DN4_ID_GENERATOR")
    private java.lang.Long id;

    public DN4() {
    }
    
    public DN4(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}