package us.dit.ass.primeraconsultaneurologica;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class dolorNeuropatico implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Nivel del dolor Neuropatico detectado")
	private int nivel;

	public dolorNeuropatico() {
	}

	public int getNivel() {
		return this.nivel;
	}

	public void setNivel(int nivel) {
		this.nivel = nivel;
	}

	public dolorNeuropatico(int nivel) {
		this.nivel = nivel;
	}

}